server:
  port: 88
spring:
  # 数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/tworice_admin?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari数据库连接池
    hikari:
      minimum-idle: 2 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 5 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 0 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  #
  mail:
    host: smtp.163.com
    username: tworice_0811@163.com
    password: QZXRQQWBALLKIHSO
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:              #配置文件上传时的文件大小限制等
      enabled: true
      max-file-size: 200MB
      max-request-size: 500MB
      file-size-threshold: 200MB
# 日志输出
logging:
  level:
    root: info
    cn.tworice: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启下划线到驼峰规则的自动转换，如果数据库中字段名是user_name自动映射成userName
    map-underscore-to-camel-case: true
    # 开启MyBatis二级缓存
    cache-enabled: true
tworice:
  login:
    captchaAging: 300000 # 验证码的有效时间（毫秒）
    root: root-root # 超级管理员账户
  generate:
    vue-project: tworice-admin-web # 前端项目与当前项目平级的相对路径，要包含前端项目根路径
    template: template  # 代码生成模板在resources目录下的路径
  dev: true
  file:
    path: \target\classes\static\

  alipay:
    appid: 2021000122602703