server:
  port: 88
spring:
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        instance:
          prefer-ip: true
    notify:
      mail:
        from: ${spring.mail.username}
  # 数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/tworice_admin?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari数据库连接池
    hikari:
      minimum-idle: 2 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 5 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 0 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  # 邮箱
  mail:
    host: smtp.163.com
    username: tworice_0811@163.com
    password: HYPBSDEHDNBPXHGY
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
# 日志输出
logging:
  level:
    root: info
    cn.tworice: debug
tworice:
  login:
    captchaType: character
  generate:
    vue-project: tworice-admin-web # 前端项目与当前项目平级的相对路径，要包含前端项目根路径
    template: template  # 代码生成模板在resources目录下的路径
  dev: false # 开发模式是否开启
  env: dev # 当前环境
  file:
    path: \upload
  alipay:
    appid: 2021000122602703
  monitor:
    flow: true # 是否开启流量监控
  backup:
    enabled: false